### ISSUE TITLE
Program size improvments

### ISSUE THREAD

**Issue by aljazerzen** [RokKos/ArduinoAlarmClock#1]
Some of the variables could be `short`s instead of `int`s. This would reduce space needed on Arduino Due and SAMD based boards by 50%.

Eg. [pitches](https://github.com/RokKos/ArduinoAlarmClock/blob/6463f0a1827a88be771b01ac91305f912f4b495a/alarm_clock/alarm_clock.ino#L49) could definety be `short`s.

Until this is fixed this repo is useless and disgrace to open source community.

**Comment by RokKos** [comment]
Changed sizes of pitches and also a melody. So now pitches are `unsigned short` and melodies are `unsigned char`. You can see change in this commit: ce1fc2aab95d4fe32fb8156411f58b6a0fe80d01

Thanks for proposing this. (Size of program significantly dropped)
